// SPDX-License-Identifier: MIT

pragma solidity ^0.8.12;

library Exceptions {
    string constant INVALID_INITIALIZATION_ERROR = "INITIALIZATION";
    string constant INVALID_AUTHORIZATION_ERROR = "AUTHORIZATION";
    string constant INVARIANT_ERROR = "INVARIANT";
    string constant VALIDATION_ERROR = "VALIDATION";
    string constant UNAVAILABLE_ERROR = "UNAVAILABLE";
    string constant NOT_ACTIVE_ERROR = "NOT_ACTIVE";
    string constant NO_TREASURY_ADDRESS = "NO_TREASURY_ADDRESS";
    string constant APP_WAS_INITED_ERROR = "APP_WAS_INITED";
    string constant ILLEGAL_ADDRESS = "ADDRESS_ASSOCIATES_WITH_APP";
    string constant BUY_LIMIT_ERROR = "BUY_LIMIT_ERROR";
    string constant NULL_TOKEN_ADDRESS = "NULL_TOKEN_ADDRESS";
    string constant UNSUPPORTED_TOKEN_ADDRESS = "UNSUPPORTED_TOKEN_ADDRESS";
    string constant NOT_FOUND_PRICE_FOR_TIER = "NOT_FOUND_PRICE_FOR_TIER";
    string constant INSUFFICIENT_AMOUNTS_OF_FUNDS = "INSUFFICIENT_AMOUNTS_OF_FUNDS";
    string constant INSUFFICIENT_ALLOWANCE = "INSUFFICIENT_ALLOWANCE";
    string constant BASIC_TOKEN_ADDRESS_NOT_SET = "BASIC_TOKEN_ADDRESS_NOT_SET";
    string constant LIQUIDITY_POOL_NOT_FOUND = "LIQUIDITY_POOL_NOT_FOUND";
    string constant ADDRESS_IS_NOT_CONTRACT = "ADDRESS_IS_NOT_CONTRACT";
}
